name: dva
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - comm=0.2.3
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - intel-openmp=2023.1.0
  - ipykernel=7.0.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - matplotlib-inline=0.2.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - narwhals=2.7.0
  - nest-asyncio=1.6.0
  - numexpr=2.11.0
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.5.0
  - plotly=6.3.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.1
  - pure_eval=0.2.3
  - pydeck=0.9.1
  - pygments=2.19.2
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pywin32=311
  - pyzmq=27.1.0
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tbb=2021.8.0
  - tk=8.6.15
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - altair==5.5.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorama==0.4.6
      - geopandas==1.1.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.11
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - pillow==11.3.0
      - protobuf==6.33.0
      - pyarrow==21.0.0
      - pyogrio==0.11.1
      - pyproj==3.7.1
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.28.0
      - shapely==2.1.2
      - smmap==5.0.2
      - streamlit==1.50.0
      - tenacity==9.1.2
      - toml==0.10.2
      - tornado==6.5.2
      - urllib3==2.5.0
      - watchdog==6.0.0
prefix: C:\Users\jh\miniconda3\envs\dva
